Areas/Admin/Controllers/SkillsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using dona.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using dona.Model;
using PagedList.Core;
namespace dona.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SkillsController : Controller
    {
        private readonly Datacontext _context;

        public SkillsController(Datacontext context)
        {
            _context = context;
        }

       [Route("/Admin/skill-index/{page:int}.html", Name ="killIndex")]
       public IActionResult Index(int page = 1)
       {
         var skill = _context.Skills.OrderByDescending(p => p.SkillID);
        int pageSize = 5;
        PagedList<tblSkills> models = new(skill, page, pageSize);
        if (models == null)
        return NotFound();
        return View(models);
        }


        public IActionResult Index()
          {
             return RedirectToRoute("killIndex", new { page = 1 });
          }


        public  IActionResult Delete(long? id)
        {
            if(id==null || id==0) 
            return NotFound();
            var mn=_context.Skills.Find(id);
            if(mn==null)
            return NotFound();
            return View(mn);
        }
        
        [HttpPost]
        public IActionResult Delete(long id)
        {
            var delpath=_context.Skills.Find(id);
            if(delpath==null)
            return NotFound();
            _context.Skills.Remove(delpath);
            _context.SaveChanges();
            return RedirectToAction("Index");
            }

             public IActionResult Create()
        {
            var mnList = (from m in _context.Champions
                          select new SelectListItem()
                          {
                              Text = m.NameChampions,
                              Value = m.ChampionsID.ToString()
                          }).ToList();

            mnList.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = string.Empty
            });

            ViewBag.mnlist = mnList;
            return View();
        }

        [HttpPost]
        public IActionResult Create(tblSkills cham)
        {
            if (ModelState.IsValid)
            {
                _context.Skills.Add(cham);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
 public IActionResult Edit(long? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var mn = _context.Skills.Find(id);
            if (mn == null)
                return NotFound();

            var mnList = (from m in _context.Champions
                          select new SelectListItem()
                          {
                              Text = m.NameChampions,
                              Value = m.ChampionsID.ToString()
                          }).ToList();

            mnList.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = string.Empty
            });

            ViewBag.mnList = mnList;
            return View(mn);
        }

        [HttpPost]
        public IActionResult Edit(tblSkills path)
        {
            if (ModelState.IsValid)
            {
                _context.Skills.Update(path);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        }
    }

Areas/Admin/Views/Skills/Create.cshtml
@using dona.Areas.Admin.Models
@using dona.Utilities;
@model dona.Model.tblSkills
    
    @{
        Layout="~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    }
    <main id="main" class="main">
        <div class="pagetitle">
            <h4> Skill management >  Add a new Skill</h4>
            <hr />
            <div class="row">
                <div class="col-md-12">
                    <form asp-action="Create" method="Post">
                        <div class="form-group col-md-6 mb-3">
                            <label>  Menu Skill</label>
                            <select asp-for="ChampionsID" class="form-control"
                        asp-items="@(new SelectList(ViewBag.mnList,"Value","Text"))" id="ChampionsID"></select>
                        </div>  
                        <div class="form-group">
                            <label class="control-label">Name skills</label>
                            <input asp-for="Nameskill" class="form-control"/>
                            <span asp-validation-for="Nameskill" class="text-danger mb-4"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Description</label>
                            <textarea asp-for="Description" class="form-control" row="6"></textarea>
                            <span asp-validation-for="Description" class="text-danger mb-4"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Image</label>
                            <div class="input-group mb-3">
                            <div class="input-group-prepend">
                            <button class="btn btn-success" type="button" onclick="openDialog()">Choose an image</button>
                        </div>
                            <input type="text" class="form-control"asp-for="Images"id="file-input"
                        aria-describedby="button-addon2">
                        </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">author</label>
                            <textarea asp-for="author" class="form-control" ></textarea>
                            <span asp-validation-for="author" class="text-danger mb-4"></span>
                        </div>
<div class="form-group d-none">
    <input asp-for="createted_Date" class="form-control" value="@Functions.getCurrentDate()"/>
</div>

<div class="form-group">
    <label>
        @Html.CheckBox("IsActive",false)
        Visible
    </label>
</div>
<div class="form-group mt-5">
    <button type="submit" value="Create" class="btn btn-primary"asp-action="Create"
    onclick="return checkValue()">Sav Information</button>
</div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    @{
        var SummerNote=new dona.Areas.Admin.Models.SummerNote("#Contents");
        <partial name="_SummerNote" model="SummerNote"/>
    }

Areas/Admin/Views/Skills/Delete.cshtml
@using dona.Areas.Admin.Models
@using dona.Utilities;
@model dona.Model.tblSkills
    @{
        Layout="~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    }
    <main id="main" class="main">
        <div class="pagetitle">
            <h2> Confirm to delete a Skill</h2>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="SkillID">SkillID</label>
                <input type="text" class="form-control mb-3"asp-for="SkillID"disabled />
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Nameskill">Nameskill</label>
                <input type="text" class="form-control mb-3"asp-for="Nameskill" disabled />
            </div>
        </div>
        <form asp-action="Delete" method="Post">
            <input type="hidden"asp-for="SkillID" />
            <a class="btn btn-lg-btn-warning p-2 mr-5"href="javacript:history.back()">
                <i class="bi bi-arrow-left-circle"></i> Go back
            </a>
            <button type="submit" class="btn btn-lg btn-danger p-2">
                <i class="bi bi-trash"></i>Delete
            </button> 
        </form>
    </main>

Areas/Admin/Views/Skills/Edit.cshtml
@using dona.Areas.Admin.Models
@using dona.Utilities;
@model dona.Model.tblSkills
    
    @{
        Layout="~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    }
    <main id="main" class="main">
        <div class="pagetitle">
            <h4> Skill management >  Edit a new Skill</h4>
            <hr />
            <div class="row">
                <div class="col-md-12">
                    <form asp-action="Edit" method="Post">
                        <div class="form-group col-md-6 mb-3">
                            <label>  Menu Skill</label>
                            <input type="text" class ="form-control" asp-for="SkillID" type="hidden">
                            <select asp-for="ChampionsID" class="form-control"
                        asp-items="@(new SelectList(ViewBag.mnList,"Value","Text"))" id="ChampionsID"></select>
                        </div>  
                        <div class="form-group">
                            <label class="control-label">Name skills</label>
                            <input asp-for="Nameskill" class="form-control"/>
                            <span asp-validation-for="Nameskill" class="text-danger mb-4"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Description</label>
                            <textarea asp-for="Description" class="form-control" row="6"></textarea>
                            <span asp-validation-for="Description" class="text-danger mb-4"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Image</label>
                            <div class="input-group mb-3">
                            <div class="input-group-prepend">
                            <button class="btn btn-success" type="button" onclick="openDialog()">Choose an image</button>
                        </div>
                            <input type="text" class="form-control"asp-for="Images"id="file-input"
                        aria-describedby="button-addon2">
                        </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">author</label>
                            <textarea asp-for="author" class="form-control" ></textarea>
                            <span asp-validation-for="author" class="text-danger mb-4"></span>
                        </div>
<div class="form-group d-none">
    <input asp-for="createted_Date" class="form-control" value="@Functions.getCurrentDate()"/>
</div>

<div class="form-group">
    <label>
        @Html.CheckBox("IsActive",false)
        Visible
    </label>
</div>
<div class="form-group mt-5">
    <button type="submit" value="Edit" class="btn btn-primary"asp-action="Edit"
    onclick="return checkValue()">Sav Information</button>
</div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    @{
        var SummerNote=new dona.Areas.Admin.Models.SummerNote("#Contents");
        <partial name="_SummerNote" model="SummerNote"/>
    }

Areas/Admin/Views/Skills/Index.cshtml
@using dona.Model
@using dona.Models;
@using PagedList.Core.Mvc;
@model PagedList.Core.IPagedList<tblSkills>
    
    @{
        Layout="~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    }
    <main id="main"class ="main">
        <div class="pagetitle">
            <h2>List of Skill</h2>
            <div class="col-4">
                <a type="button" class="btn btn-success"asp-area="Admin"asp-controller="Skills"asp-action="Create">
    <i class="bi bi-file-earmark-text me-1"></i>Add a new Skills
</a>
            </div>
            <div class="col-8">
                <div>
                    <ul class ="pagination float-erd">
                        <pager class="pager-container" options="@PagedListRenderOptions.Bootstrap4PageNumbersOnly" list="@Model"></pager>
                    </ul>
                    </div>
            </div>
        </div>

                <section class ="section dashboard">
                        <div class="row">
    
                            <div  class="col-12">
    
                                <div class="card recent-sales overflow-auto">
                                    <div class="card-body mt-4 ">
                                        <table class="table table-borderless datatable">
                                            <thead>
                                                <tr>
                                                    <th class="col-1 text-center">skillID</th>
                                                     <th class="col-4 text-center">Name</th>
                                                      <th class="col-2 text-center"> Funtions</th>
                                                      <th class="col-2 text-center">Images</th>
                                                           
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach(var item in Model)
                                                {
                                                    <tr>
                                                       
                                                <td class="text-center" scope="row">@item.SkillID</td>   
                                                <td class="text-left text-primary"scope="row">
                                                   
                                                   <a  asp-controller="Skills"asp-action="Details"
                                                asp-route-id="@item.SkillID" class="text-primary">@item.Nameskill</a>
                                                </td>
                                                <td class="text-center" scope="row">
                                                    <a asp-area="Admin"asp-controller="Skills" asp-action="Edit"
                                                asp-route-id="@item.SkillID" class="btn btn-primary btn-sm" title="Edit the Post"><i class="bi bi-pencil"></i></a>
                                                    <a asp-area="Admin" asp-controller="Skills" asp-action="Delete"
                                                asp-route-id="@item.SkillID" class="btn btn-danger btn-sm" title="Delete the Post"><i class="bi bi-trash"></i></a>
                                                 
                                                        <td class="text-center" scope="row">
                                                                 <div class="circle-image">
                                                                      <img src="@item.Images" alt="Post Image" class="responsive-image" style="max-width:50px ;height: auto; "/>
                                                                       </div>
                                                                         </td>   
                                                </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                </section>
             
        </div>
    </main>